### ISSUE TITLE
partition/replica configuration

### ISSUE THREAD

**Issue by konstan** [DarioBalinzo/kafka-connect-elasticsearch-source#33]
Is it possible to add configuration parameters to set partition/replica value for the topics created by the connector?
At the moment the connector creates 1/1.

I have ksqldb streams reading from the topics. They expect partition/replica configurations other than 1/1.

**Comment by DarioBalinzo** [comment]
Hi, I think that this config is out of scope for the elastic connector since it is already covered in the connect config (the framework running several connectors, like the elastic source connector). 

Here you can find the the relevant documentation: https://docs.confluent.io/home/connect/userguide.html#source-connector-properties

But I think that the number  of replica and partitions of new topics also depend on the settings in the Kafka brokers.

Hope this can help.
